### ISSUE TITLE
使用 BAAI/bge-reranker-v2-minicpm-layerwise  程序会重启

### ISSUE THREAD

**Issue by itchangc** [AIDotNet/AntSK#107]
/// <summary>
/// 模型写死
/// </summary>
public static dynamic LoadModel(string pythondllPath, string modelName)
{
    lock (lockobj)
    {
        if (model == null)
        {
            PyRunTime.InitRunTime(pythondllPath);
            try
            {
                using (GIL())// 初始化Python环境的Global Interpreter Lock)
                {
                    dynamic modelscope = Py.Import("modelscope");
                    dynamic flagEmbedding = Py.Import("FlagEmbedding");
                    dynamic model_dir = modelscope.snapshot_download(modelName, revision: "master");

                    if (modelName == "BAAI/bge-reranker-v2-minicpm-layerwise")
                    {
                        dynamic flagReranker = flagEmbedding.LayerWiseFlagLLMReranker(model_dir, use_fp16: true);
                        model = flagReranker;
                    }
                    else
                    {
                        dynamic flagReranker = flagEmbedding.FlagReranker(model_dir, use_fp16: true);
                        model = flagReranker;
                    }
                    return model;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        else
        {
            return model;
        }
    }
}

下面是调用数据：
 PyList cutoffLayers = new PyList();
 cutoffLayers.Append(new PyInt(8));
 dynamic scores = model.compute_score(pyList, cutoff_layers: cutoffLayers);

执行  model.compute_score  就重启。
![image](https://github.com/user-attachments/assets/777fa732-e79d-420a-806b-ad8244eec7d6)

**Comment by xuzeyu91** [comment]
看报错信息是端口被占用
