### ISSUE TITLE
报错：END CONTENT TO SUMMARIZE

### ISSUE THREAD

**Issue by jiangguanghe** [AIDotNet/AntSK#23]
END CONTENT TO SUMMARIZE.

Summarize the conversation in 'CONTENT TO SUMMARIZE', identifying main points of discussion and any conclusions that were reached.
Do not incorporate other general knowledge.
Summary is in plain text, in complete sentences, with no markup or tags.

BEGIN SUMMARY:

![image](https://github.com/xuzeyu91/AntSK/assets/22929060/d0b88f38-8f75-4bcd-880d-51d87e6cc908)

聊天，第二次就抛出这个异常，然后就答非所问，换了几个不同的模型也是这个问题

**Comment by jiangguanghe** [comment]
![image](https://github.com/xuzeyu91/AntSK/assets/22929060/f407e109-d6d6-4f18-8500-b53f674a5c41)

**Comment by xuzeyu91** [comment]
更新一下试试呢
