### ISSUE TITLE
能加一个对导入的文档做关键信息提取吗

### ISSUE THREAD

**Issue by jiangguanghe** [AIDotNet/AntSK#31]
目前只有对文档的聊天问答，导入的相似文档一多，然后答案就一大堆了，还得人为去甄别这些答案的真伪，如果能定义一些提取的关键字的模板，然后用这些模板去对文档做信息提取，针对每个文档都有一份它自己的摘要或者关键信息，这样查某个文档里的关键内容就更加准确和方便了

**Comment by xuzeyu91** [comment]
是一个不错的提议

**Comment by xuzeyu91** [comment]
该问题先关闭 后面在计划是否添加该功能
