### ISSUE TITLE
聊天消息发出后就会自动退出

### ISSUE THREAD

**Issue by duyanming** [AIDotNet/AntSK#39]
![image](https://github.com/AIDotNet/AntSK/assets/17999146/86e67263-5bed-4d70-8d95-93e6f00cd7dd)
![image](https://github.com/AIDotNet/AntSK/assets/17999146/8571ed35-e1d6-4ecd-a16d-81318b857681)

**Comment by duyanming** [comment]
![1711258638578](https://github.com/AIDotNet/AntSK/assets/17999146/e0abda7f-8ce5-4784-b48b-887aafc3e78f)

**Comment by xuzeyu91** [comment]
使用了不支持的模型

**Comment by duyanming** [comment]
谢谢
