### ISSUE TITLE
问题请教，【聊天】 让用200字形容【北京旅游】，却一直停不下来。不停重复

### ISSUE THREAD

**Issue by duyanming** [AIDotNet/AntSK#40]
![1711274851283](https://github.com/AIDotNet/AntSK/assets/17999146/9ed2f6db-acc4-4243-b34c-8b8cdbb30b7f)

![1711274804168](https://github.com/AIDotNet/AntSK/assets/17999146/67b71297-b187-483a-9ea0-982c766b086a)

**Comment by xuzeyu91** [comment]
使用的什么模型，如果出现循环一般是模型智力不行

**Comment by duyanming** [comment]
非常感谢你的回复。
我用的示例中给的这个
qwen1_5-1_8b-chat-q8_0.gguf。

是否可以推荐一个，个人电脑可以运行起来的。
谢谢

**Comment by xuzeyu91** [comment]
> 非常感谢你的回复。
> 我用的示例中给的这个
> qwen1_5-1_8b-chat-q8_0.gguf。
> 
> 是否可以推荐一个，个人电脑可以运行起来的。
> 谢谢

可以使用新版本的llamafactory支持更多的模型 例如gemma
