### ISSUE TITLE
一直报错" LLamaSharp.FileDirectory目录配置不正确！"

### ISSUE THREAD

**Issue by zckdxefbbe066** [AIDotNet/AntSK#51]
![image](https://github.com/AIDotNet/AntSK/assets/117494814/f0c1c2b6-8901-400e-8536-a1212b6ece05)
![image](https://github.com/AIDotNet/AntSK/assets/117494814/f85a0906-a3d4-4f20-87f3-4cdbb7443ec3)
 "FileDirectory": "D:\\learningNew\\AI\\AI_local_modes\\"
  "FileDirectory": "D:\\learningNew\\AI\\AI_local_modes"

 这个2中配置了 ,都不对

**Comment by xuzeyu91** [comment]
如果是容器不是 该目录需要为容器内目录，可以把本地目录进行挂载
