### ISSUE TITLE
添加“知识库”报错，该控件数据类型绑定错误调整后修复该问题。

### ISSUE THREAD

**Issue by 492400219** [AIDotNet/AntSK#63]
<FormItem Label="最低相似度（%）" LabelCol="LayoutModel._formItemLayout.LabelCol" WrapperCol="LayoutModel._formItemLayout.WrapperCol">
              <Slider TValue="double" Style="display: inline-block;width: 300px; " Min="0" Max="100" DefaultValue="70" @bind-Value="@context.Relevance" />
          </FormItem>
        /// <summary>
        /// 相似度
        /// </summary>
        [SugarColumn(DefaultValue = "70")]
        public double Relevance { get; set; } = 70;

**Comment by xuzeyu91** [comment]
该问题已修复
