### ISSUE TITLE
导入知识库时直接崩溃

### ISSUE THREAD

**Issue by then10111** [AIDotNet/AntSK#78]
<img width="843" alt="image" src="https://github.com/AIDotNet/AntSK/assets/167739712/48926a2a-3357-44a5-a074-af1e955978cb">
导入知识库时，报上面的错误

**Comment by then10111** [comment]
数据模型：qwen:0.5b，向量模型：bge-large-zh1.5，没有GPU。
服务器配置：
<img width="564" alt="image" src="https://github.com/AIDotNet/AntSK/assets/167739712/1438d6bb-944d-4590-9963-357d98d74920">
<img width="556" alt="image" src="https://github.com/AIDotNet/AntSK/assets/167739712/0c85a018-df88-4b41-8bb0-6cacb6b2ac1f">

**Comment by xuzeyu91** [comment]
看你截图似乎向量也是使用的llamasharp而并非bge embedding
