### ISSUE TITLE
使用docker运行，antskpg一直再restarting

### ISSUE THREAD

**Issue by wobuhuibei** [AIDotNet/AntSK#86]
![屏幕截图 2024-05-07 135330](https://github.com/AIDotNet/AntSK/assets/115989854/505def47-c3f6-4970-81b1-7de27bf2d773)
![屏幕截图 2024-05-07 135455](https://github.com/AIDotNet/AntSK/assets/115989854/f2a99faf-a836-4e06-965b-11a65c9c8c38)

**Comment by xuzeyu91** [comment]
配置文件是否按操作进行了挂载

**Comment by wobuhuibei** [comment]
docker-compose.yml以及appsetting.json文件截图如下，并且上图打印了antskpg的logs，感觉是antskpg跑postgres的时候出现问题，有点不解
![屏幕截图 2024-05-08 230350](https://github.com/AIDotNet/AntSK/assets/115989854/2f0659ca-900b-4d1a-9e0c-0dab4d207dcc)
：
![屏幕截图 2024-05-08 230314](https://github.com/AIDotNet/AntSK/assets/115989854/29515be1-5269-47b8-82c8-eee039e58896)

**Comment by xuzeyu91** [comment]
从截图中我并没有看到你挂载了appsetting.json 
![image](https://github.com/AIDotNet/AntSK/assets/26290929/5a68a52a-2cfb-4e77-a1ed-f206e93b0954)

**Comment by xuzeyu91** [comment]
另外你可以尝试把DB的连接改为宿主机IP
