### ISSUE TITLE
对话中调用function  ToolCallBehavior 为什么选EnableKernelFunctions 而不是AutoInvokeKernelFunctions

### ISSUE THREAD

**Issue by yc-2503** [AIDotNet/AntSK#89]

**Comment by xuzeyu91** [comment]
AutoInvokeKernelFunctions  会传递所有Function 而 EnableKernelFunctions只传递我需要的Function，
函数调用随着函数列表的增长 准确率会逐步下降，而Semantic Function 对于 Function Call来说并没有意义，所以它们应该被过滤掉

**Comment by xuzeyu91** [comment]
By the way, the probability of encountering issues when using GPT3.5 is much higher than GPT4, and I suspect it may be due to some issues with the model's understanding ability
